image: node:4

stages:
    - update
    - notify

variables:
  GIT_STRATEGY: fetch

cache:
    paths:
        - node_modules/

update_hash:
    tags:
        - docker-executor
    stage: update
    only:
        - triggers
    script:
        - if [[ -n "${UPDATE_HASH_PROJECT_ID}" && -n "${UPDATE_HASH_REPO}" && "${UPDATE_HASH_BRANCH}" && "${UPDATE_HASH_FILE}" ]]; then
        -     apt-get update
        -     apt-get install -y unzip
        -     ./build/updateHash.sh "${UPDATE_HASH_PROJECT_ID}" "${UPDATE_HASH_REPO}" "${UPDATE_HASH_BRANCH}" "${UPDATE_HASH_FILE}" "${UPDATE_HASH_BUILD_ID}"
        -     ./build/commitAndPush.sh
        - fi

 # Do not run when triggered:
 #   - triggers will end up doing a commit and the commit runs notify
notify:
    tags:
        - docker-executor
    stage: notify
    except:
        - master
        - triggers
    script:
        - if [[ "$AUTO_NOTIFY" == true ]]; then
        -     echo 'Running notifyProjects.sh'
        -     ./build/notifyProjects.sh
        - else
        -     echo AUTO_NOTIFY is off, skipping notification.
        - fi